application: infintropolis
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on

handlers:
# Images and fonts.
- url: /img/(.*\.(png|gif|jpg|woff|ttf))
  static_files: static/img/\1
  upload: static/img/(.*\.(png|gif|jpg|woff|ttf))

# Static pages.
- url: /static
  static_dir: static/web

# Profiler.
- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

# Map interface.
- url: /map
  static_files: static/web/map.htm
  upload: static/web/map.htm

# Scripts.
- url: /.*
  script: handler.py
