application: infintropolis
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# Images and fonts.
- url: /img/(.*\.(png|gif|jpg|woff|ttf))
  static_files: static/img/\1
  upload: static/img/(.*\.(png|gif|jpg|woff|ttf))

# Static pages.
- url: /static
  static_dir: static/web

# Map interface.
- url: /map
  static_files: static/web/map.htm
  upload: static/web/map.htm

# Scripts.
- url: /.*
  script: handler.app
